adding validation

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -34,8 +34,8 @@ jobs:
           for dir in $(find ./overlays -maxdepth 1 -type d); do
             if [ -f "$dir/kustomization.yaml" ]; then
               echo "Processing Kustomize directory: $dir"
-              if ! kustomize build $dir | kubeconform &> /dev/null; then
-                echo "Kustomize build failed in directory: $dir"
+              if ! kustomize build $dir | kubeconform -verbose; then
+                echo "Build failed in directory: $dir"
                 exit 1
               fi
             fi
